### ISSUE TITLE
1.0.7 build fails after npm instal on blazor wasm                        

### ISSUE THREAD

**Issue by demetrixezz** [TrevorMare/STGTour#6]
![image_2022_04_12T20_14_28_900Z](https://user-images.githubusercontent.com/1817070/163047747-8ce265b8-5ede-4021-bee8-8fa77c573158.png)
that what happens after instalation on blazor wasm

**Comment by TrevorMare** [comment]
This was due to a tsconfig file that shipped as part of the Nuget package. I have removed it now and published a new version to Nuget 1.0.8.
